import type { components } from "@hisob24/api-client"

// The user app API's records, as openapi.yaml describes them.
export type Tokens = components["schemas"]["Tokens"]
export type Me = components["schemas"]["Me"]
export type AppCompany = components["schemas"]["AppCompany"]
export type Role = components["schemas"]["Role"]
export type Member = components["schemas"]["Member"]
export type Permission = components["schemas"]["Permission"]
export type CompanyRole = components["schemas"]["CompanyRole"]
export type CustomerOption = components["schemas"]["CustomerOption"]
export type CustomerDropdown = components["schemas"]["CustomerDropdown"]
export type CustomerFieldKind = components["schemas"]["CustomerFieldKind"]
export type CustomerField = components["schemas"]["CustomerField"]
export type CustomerType = components["schemas"]["CustomerType"]
export type Customer = components["schemas"]["Customer"]
export type CustomerValues = components["schemas"]["CustomerValues"]
export type CustomerAnswers = components["schemas"]["CustomerAnswers"]
export type CustomerPage = components["schemas"]["CustomerPage"]
export type CustomerHistoryEntry = components["schemas"]["CustomerHistoryEntry"]
export type StageColor = components["schemas"]["StageColor"]
export type TaskStage = components["schemas"]["TaskStage"]
export type TaskField = components["schemas"]["TaskField"]
export type TaskType = components["schemas"]["TaskType"]
export type Task = components["schemas"]["Task"]
export type TaskCustomer = components["schemas"]["TaskCustomer"]
export type TaskAssignee = components["schemas"]["TaskAssignee"]
export type TaskCreate = components["schemas"]["TaskCreate"]
export type TaskCustomerInput = components["schemas"]["TaskCustomerInput"]
export type TaskUpdate = components["schemas"]["TaskUpdate"]
export type TaskPage = components["schemas"]["TaskPage"]
export type TaskHistoryEntry = components["schemas"]["TaskHistoryEntry"]
